<?php

/**
 * @file
 * Countdown timer field module allows you to create countdown timer
 * field to count the days, hours, minutes, and seconds until a specified
 * event.
 */

/**
 * Implements hook_field_widget_settings_form().
 */
/**
function field_countdown_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  $form['font_size'] = array(
    '#type' => 'textfield',
    '#title' => t('Font Size'),
    '#description' => t('Size of the timer will depend upon this value.'),
    '#default_value' => isset($settings['font_size']) ? $settings['font_size'] : NULL,
    '#required' => TRUE,
    '#element_validate' => array('_element_validate_integer_positive'),
  );

  return $form;
}
**/

/**
 * Implements hook_field_formatter_info().
 */
function field_countdown_field_formatter_info() {
  return array(
    'field_countdown_default' => array(
      'label' => t('jQuery Countdown Timer without text timer'),
      'field types' => array('field_countdown'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
    'field_countdown_with_text_timer' => array(
      'label' => t('jQuery Countdown Timer with text timer'),
      'field types' => array('field_countdown'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
    'field_countdown_plain' => array(
      'label' => t('Date and time as string'),
      'field types' => array('field_countdown'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
    'field_countdown_integer' => array(
      'label' => t('Unix time stamp'),
      'field types' => array('field_countdown'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
/**
function field_countdown_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $countdown_field_count = &drupal_static(__FUNCTION__);
  if (empty($countdown_field_count)) {
    $countdown_field_count = 0;
  }
  switch ($display['type']) {
    case 'field_countdown_default':
      foreach ($items as $delta => $item) {
        if (time() < $item['countdown_timer']) {
          $element[$delta]['#markup'] = _field_countdown_display_timer(
              check_plain($item['countdown_timer']), $instance['widget']['settings']['font_size'], $countdown_field_count, FALSE);
          $countdown_field_count++;
        }
      }
      break;

    case 'field_countdown_with_text_timer':
      foreach ($items as $delta => $item) {
        if (time() < $item['countdown_timer']) {
          $element[$delta]['#markup'] = _field_countdown_display_timer(
              check_plain($item['countdown_timer']), $instance['widget']['settings']['font_size'], $countdown_field_count, TRUE);
          $countdown_field_count++;
        }
      }
      break;

    case 'field_countdown_plain':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = date('Y-m-d H:i', check_plain(
                $item['countdown_timer'])
        );
      }
      break;

    case 'field_countdown_integer':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = check_plain($item['countdown_timer']);
      }
      break;
  }

  return $element;
}
**/

/**
 * Creates the jquery countdown timer.
 */
function _field_countdown_display_timer($time, $font_size, $countdown_field_count, $text_timer = FALSE) {
  $path = libraries_get_path('jquery-countdown');
  drupal_add_js($path . '/assets/countdown/jquery.countdown.js', array(
    'type' => 'file', 'scope' => 'footer',
      )
  );
  $suffix = str_replace(array('.', ' '), array('-', '-'), microtime());
  $settings = array(
    'coundownSetting' . $countdown_field_count => array(
      'coundownSetting_suffix' => $suffix,
      'coundownSetting_time' => $time,
    ),
  );
  drupal_add_js(array('field_countdown' => $settings), 'setting');
  drupal_add_js(drupal_get_path('module', 'field_countdown') . '/field_countdown.js', array(
    'scope' => 'footer', 'weight' => 5,
  ));

  drupal_add_css($path . '/assets/countdown/jquery.countdown.css');
  drupal_add_css(
      '.countdownHolder {font-size: ' . $font_size . 'px}', 'inline'
  );

  $content = theme('field_countdown_timer', array(
    'text_timer' => $text_timer,
    'suffix' => $suffix,
      )
  );

  return $content;
}

/**
 * Returns HTML for the timer container.
 */
function theme_field_countdown_timer($variables) {
  $output = '';
  $output .= "<div id='field-countdown-timer-" . $variables['suffix'] . "'>
    </div>";
  if ($variables['text_timer']) {
    $output .= "<div id='field-countdown-timer-note-" . $variables['suffix'] .
        "'></div>";
  }
  else {
    $output .= "<div style='display:none;' id='field-countdown-timer-note-" .
        $variables['suffix'] . "'></div>";
  }

  return $output;
}
