<?php

/**
 * @file
 * Contains alter hooks, validation and theme functions.
 *
 * Countdown timer field module allows you to create countdown timer
 * field to count the days, hours, minutes, and seconds until a specified
 * event.
 */

module_load_include('inc', 'field_countdown2', 'field_countdown2.field');

/**
 * Implements hook_field_widget_info_alter().
 */
function date_field_widget_info_alter(&$info) {
  $info['date_text']['field types'][] = 'field_countdown2';
  $info['date_select']['field types'][] = 'field_countdown2';

  if (module_exists('date_popup')) {
    $info['date_popup']['field types'][] = 'field_countdown2';
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function date_field_widget_form_alter(&$element, &$form_state, $context) {
  $field = $context['field'];
  $instance = $context['instance'];
  $items = $context['items'];
  $delta = $context['delta'];

  if ($field['type'] === 'field_countdown2') {
    $default = isset($items[$delta]['visibility']) ?
      $items[$delta]['visibility'] : $field['settings']['visibility'];
    $element['visibility'] = array(
      '#type' => 'checkbox',
      '#title' => t('Visible'),
      '#default_value' => $default,
    );
    $element['#element_validate'] = array('field_countdown2_validate');
  }
}

/**
 * Validate and update a field_countdown2 element.
 *
 * Don't try this if there were errors before reaching this point.
 */
function field_countdown2_validate($element, &$form_state) {
  module_load_include('inc', 'date', 'date_elements');
  $element['value']['#field']['type'] = 'datestamp';
  date_combo_validate($element, $form_state);
  $element['value']['#field']['type'] = 'field_countdown2';
}

/**
 * Creates the jquery countdown timer.
 */
function field_countdown2_display_timer(&$element, $time, $font_size, $font_size_note, $text_timer = FALSE) {
  $countdown_field_id = drupal_html_id("countdown-timer-countdown");
  $note_id = drupal_html_id("countdown-timer-note");
  $settings = array(
    $countdown_field_id => array(
      'countdown-settings-time' => $time,
    ),
  );

  $path = drupal_get_path('module', 'field_countdown2');
  $element['#attached']['js'][] = array(
    'data' => $path . '/jquery_countdown/countdown/jquery.countdown.js',
    'type' => 'file',
    'scope' => 'footer',
  );
  $element['#attached']['js'][] = array(
    'data' => $path . '/field_countdown2.js',
    'type' => 'file',
    'scope' => 'footer',
    'weight' => 5,
  );
  $element['#attached']['js'][] = array(
    'data' => array('field_countdown2' => $settings),
    'type' => 'setting',
  );
  $element['#attached']['css'][] = array(
    'data' => $path . '/jquery_countdown/countdown/jquery.countdown.css',
    'type' => 'file',
  );
  $element['#attached']['css'][] = array(
    'data' =>
    '#' . $countdown_field_id . ' { font-size: ' . $font_size . 'px }',
    'type' => 'inline',
  );
  $element['#attached']['css'][] = array(
    'data' =>
    '#' . $note_id . ' { font-size: ' . $font_size_note . 'px }',
    'type' => 'inline',
  );
  $suffix = str_replace(array('.', ' '), array('-', '-'), microtime());

  $content = theme(
    'field_countdown2_timer',
    array(
      'timer_id' => $countdown_field_id,
      'note_id' => $note_id,
      'text_timer' => $text_timer,
    )
  );

  return $content;
}

/**
 * Implements hook_theme().
 */
function field_countdown2_theme() {
  return array(
    'field_countdown2_timer' => array(
      'template' => 'field-countdown2-timer',
      'variables' => array(
        'timer_id' => NULL,
        'note_id' => NULL,
        'text_timer' => NULL,
      ),
    ),
  );
}
