<?php

/**
 * @file
 * Contains alter hooks, validation and theme functions.
 *
 * Countdown timer field module allows you to create countdown timer
 * field to count the days, hours, minutes, and seconds until a specified
 * event.
 */

module_load_include('inc', 'field_countdown2', 'field_countdown2.field');

/**
 * Validate and update a field_countdown2 element.
 *
 * Don't try this if there were errors before reaching this point.
 */
function field_countdown2_validate($element, &$form_state) {
  module_load_include('inc', 'date', 'date_elements');
  $element['value']['#field']['type'] = 'datestamp';
  date_combo_validate($element, $form_state);
  $element['value']['#field']['type'] = 'field_countdown2';
}

/**
 * Creates the jquery countdown timer.
 */
function field_countdown2_display_timer($item, $language, $font_size) {
  $element = array(
    '#attached' => array(),
  );
  $countdown_field_id = drupal_html_id("countdown-timer-countdown");
  $settings = array(
    $countdown_field_id => array(
      'countdown-settings-time' => $item['value'],
      'countdown-settings-language' => $language,
    ),
  );

  $path = drupal_get_path('module', 'field_countdown2');
  $element['#attached']['js'][] = array(
    'data' => $path . '/flip_clock/flipclock.js',
    'type' => 'file',
    'scope' => 'footer',
  );
  $element['#attached']['js'][] = array(
    'data' => $path . '/field_countdown2.js',
    'type' => 'file',
    'scope' => 'footer',
    'weight' => 5,
  );
  $element['#attached']['js'][] = array(
    'data' => array('field_countdown2' => $settings),
    'type' => 'setting',
  );
  $element['#attached']['css'][] = array(
    'data' => $path . '/flip_clock/flipclock.css',
    'type' => 'file',
  );
  $element['#attached']['css'][] = array(
    'data' => $path . '/css/field_countdown2.css',
    'type' => 'file',
  );

  $element['#theme'] = 'field_countdown2_timer';
  $element['#timer_id'] = $countdown_field_id;
  $element['#heading'] = $item['heading'];

  return $element;
}

/**
 * Implements hook_theme().
 */
function field_countdown2_theme() {
  return array(
    'field_countdown2_timer' => array(
      'template' => 'field-countdown2-timer',
      'variables' => array(
        'timer_id' => NULL,
        'language' => NULL,
        'heading' => NULL,
      ),
    ),
  );
}
